---
- name: Create groups
  hosts: all
  become: yes
  vars_files:
    - user_list.yml
  tasks:
    - name: Add user
      vars:
        password: "{{ lookup('password', './password-' + '{{ item.name }}' + ' length=6') }}"
      user:
        name: "{{ item.name }}"
        password: "{{ 'password'| password_hash('sha512') }}" 
        uid: "{{ item.uid }}"
        comment: "{{ item.first|capitalize }} {{ item.middle|capitalize }} {{item.last|capitalize }}"
        update_password: on_create
      loop: "{{ users }}"
